name: test

on:
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust:
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.os }}

    steps:
      # - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: cargo build
        run: cargo build --all --locked --verbose

      - name: cargo test
        run: cargo test --all --locked --verbose

      - name: cargo fmt
        run: |
          rustup component add rustfmt
          cargo fmt --all -- --check
